#!/bin/sh

if [ `hostname -s` = "socket" ]; then
	~/xt_sel -geometry 111x26+0-0 &
	~/xt_sel -geometry 111x26-0-0 &
	~/xt_sel -geometry 111x26+0+0 &
	~/xt_sel -geometry 111x26-0+0 &
else
	~/xt_sel -geometry 109x27+0-0 &
	~/xt_sel -geometry 108x27-0-0 &
	~/xt_sel -geometry 109x27+0+0 &
	~/xt_sel -geometry 108x27-0+0 &
fi
