#!/bin/sh

# git config --global user.email XXXXXXXXXX@XXXXXX.XXX
git config --global user.name mcthoren
git config --global push.default simple
git config --global pull.ff only # what do i know? try this for now.
