#!/usr/local/bin/zsh

to_link=(.fvwmrc\
 .vimrc\
 .XCompose\
 .Xdefaults\
 .xinitrc\
 xl_sel\
 .xmodmaprc.ep117\
 .xmodmaprc.iva\
 .xpdfrc\
 xt_sel\
 .zshrc)

cd ~/env/ || exit 1
cd ~/ || exit 1 

for i in $to_link; do
	ln -s ~/env/$i
done

ln -s ~/env/.fvwmrc ~/.fvwm2rc
ln -s ~/env/.xinitrc ~/.xsession
ln -s ~/env/.Xdefault ~/.Xresources
