#!/usr/local/bin/zsh

NUM=$(($RANDOM%5));

[ `hostname -s` = "ep117" ] && NUM=22
[ `hostname -s` = "iva" ] && NUM=99
[ `hostname -s` = "bolt" ] && NUM=99
[ `hostname -s` = "socket" ] && NUM=64

((NUM==0)) && xlock -mode bug
((NUM==1)) && xlock -mode life 
((NUM==2)) && xlock -mode maze 
((NUM==3)) && xlock -mode pyro 
((NUM==4)) && xlock -mode grav 

((NUM==5)) && xlock -mode galaxy 
((NUM==6)) && xlock -mode fadeplot 
((NUM==7)) && xlock -mode ifs 
((NUM==8)) && xlock -mode strange 
((NUM==9)) && xlock -mode thornbird 

((NUM==22)) && {
	gnome-screensaver-command -l
	# xset dpms 240
}

((NUM==42)) && dm-tool lock

((NUM==62)) && echo "shell test"

((NUM==64)) && slock

((NUM==99)) && {
	xlock -mode blank
	# xlock -mode blanck &
	# sleep 6
	# xset dpms force standby
}
