#!/usr/local/bin/zsh

NUM=$(($RANDOM%5));

HOST_N="$(hostname -s)"

[[ "${HOST_N}" == "ep117" ]] && NUM=22
[[ "${HOST_N}" == "iva" ]] && NUM=64
[[ "${HOST_N}" == "bolt" ]] && NUM=64
[[ "${HOST_N}" == "socket" ]] && NUM=64

((NUM==0)) && xlock -mode bug
((NUM==1)) && xlock -mode life 
((NUM==2)) && xlock -mode maze 
((NUM==3)) && xlock -mode pyro 
((NUM==4)) && xlock -mode grav 

((NUM==5)) && xlock -mode galaxy 
((NUM==6)) && xlock -mode fadeplot 
((NUM==7)) && xlock -mode ifs 
((NUM==8)) && xlock -mode strange 
((NUM==9)) && xlock -mode thornbird 

((NUM==62)) && {
	gnome-screensaver-command -l
	# xset dpms 240
}

((NUM==63)) && dm-tool lock
((NUM==64)) && slock

((NUM==98)) && echo "shell test"
((NUM==99)) && {
	xlock -mode blank
	# xlock -mode blanck &
	# sleep 6
	# xset dpms force standby
}
