#!/usr/local/bin/zsh
# just go with zsh and zsh arrays


colors=(\#00e000 DeepSkyBlue DeepSkyBlue1 DeepSkyBlue2 cyan LimeGreen darkturquoise \#00a0ff MediumSpringGreen SpringGreen mediumturquoise skyblue springgreen turquoise green1 green2 green3)

NUM=$(($RANDOM%${#colors}+1));
COLOR=$colors[$NUM]

xterm $@ -fg $COLOR &
